/*
 * Copyright 2018 Syam Pillai
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.storedobject.common;

/**
 * The ErrorText class extends the HTMLText class and represents a specialized text container
 * capable of handling errors and associating error data.
 *
 * @author Syam
 */
public class ErrorText extends HTMLText {

    private Object errorObject;
    private Throwable error;

    /**
     * Default constructor for the {@code ErrorText} class.
     * This constructor initializes an instance of {@code ErrorText} without any predefined error object or error state.
     */
    public ErrorText() {
    }

    /**
     * Sets the error object associated with this instance. If an error object is already
     * set, this method will not overwrite it.
     *
     * @param errorObject the error object to be associated with this instance. This can be any object
     *                    containing error-specific details.
     */
    public void setErrorObject(Object errorObject) {
        if(this.errorObject != null) {
            return;
        }
        this.errorObject = errorObject;
    }

    /**
     * Retrieves the error object associated with this instance. The error object
     * may contain details related to an error and is typically set using the
     * {@code setErrorObject} method.
     *
     * @return the error object associated with this instance, or {@code null}
     *         if no error object has been set.
     */
    public Object getErrorObject() {
        return errorObject;
    }

    /**
     * Sets the error associated with this instance. This method will only overwrite
     * the existing error if the current error is {@code null} or if the new error
     * being set is not {@code null}.
     *
     * @param error the {@code Throwable} representing the error to be associated
     *              with this instance. It can be {@code null} to clear the error
     *              if no error is currently associated.
     */
    public void setError(Throwable error) {
        if(this.error != null && error == null) {
            return;
        }
        this.error = error;
    }

    /**
     * Retrieves the error associated with this instance.
     * The returned error is a {@code Throwable} that represents
     * the error condition, or {@code null} if no error has been set.
     *
     * @return the {@code Throwable} representing the error associated with
     *         this instance, or {@code null} if no error is present.
     */
    public Throwable getError() {
        return error;
    }

    /**
     * Checks whether an error is present in this instance.
     *
     * @return true if an error is associated with this instance, false otherwise.
     */
    public boolean isError() {
        return error != null;
    }

    /**
     * Generates and retrieves an error associated with this instance.
     * If an error is already set, it directly returns that error.
     * If no error is set and the instance is not empty, a new {@code SOException}
     * is created using the string representation of this instance.
     * If the instance is empty and no error is set, {@code null} is returned.
     *
     * @return the {@code Throwable} representing the current error, a new
     *         {@code SOException} if one needs to be generated, or {@code null}
     *         if no error is present and the instance is empty.
     */
    public Throwable generateError() {
        if(error != null) {
            return error;
        }
        if(!isEmpty()) {
            return new SOException(toString());
        }
        return null;
    }

    /**
     * Throws a {@code Throwable} error associated with this instance, if one is present.
     * The error is retrieved using the {@code generateError()} method.
     * If a {@code Throwable} is generated and is not {@code null}, it is immediately thrown.
     * If no error is generated or the error is {@code null}, the method completes without any action.
     *
     * @throws Throwable if an error is generated by {@code generateError()} and is not {@code null}.
     */
    public void throwError() throws Throwable {
        Throwable e = generateError();
        if(e != null) {
            throw e;
        }
    }

    @Override
    public ErrorText clear() {
        super.clear();
        errorObject = null;
        error = null;
        return this;
    }
}
